CreateConVar("ammokill_enabled", 1, FCVAR_ARCHIVE + FCVAR_SERVER_CAN_EXECUTE, "whether ammo on kill is enabled", 0, 1)
CreateConVar("ammo_start_with_smg_grenades", 1, FCVAR_ARCHIVE + FCVAR_SERVER_CAN_EXECUTE, "\n1 = start with 3 smg grenades\n0 = start with 0 smg grenades", 0, 1)
CreateClientConVar("ammokill_hidden", 0, true, false, "\n1 = hidden\n0 = not hidden", 0, 1)
CreateConVar("ammokill_primarymax", 10, FCVAR_ARCHIVE + FCVAR_SERVER_CAN_EXECUTE, "max primary mags reachable by ammo on kill", 0)
CreateConVar("ammokill_secondarymax", 10, FCVAR_ARCHIVE + FCVAR_SERVER_CAN_EXECUTE, "max secondary ammo reachable by ammo on kill", 0)
CreateConVar("ammokill_primary_multiplier", 1, FCVAR_ARCHIVE + FCVAR_SERVER_CAN_EXECUTE, "how many primary mags to give back per kill", 0)
CreateConVar("ammokill_secondary_multiplier", 1, FCVAR_ARCHIVE + FCVAR_SERVER_CAN_EXECUTE, "how much secondary ammo to give back per kill", 0)
CreateConVar("ammokill_headshots_only", 0, FCVAR_ARCHIVE + FCVAR_SERVER_CAN_EXECUTE, "only headshots give ammo", 0, 1)
CreateConVar("ammokill_overkills_are_headshots", 0, FCVAR_ARCHIVE + FCVAR_SERVER_CAN_EXECUTE, "should one-shots be counted as headshots?", 0, 1)
CreateConVar("ammokill_chance", 100, FCVAR_ARCHIVE + FCVAR_SERVER_CAN_EXECUTE, "chance that the kill gives ammo", 0, 100)
CreateConVar("ammokill_balanced", 0, FCVAR_ARCHIVE + FCVAR_SERVER_CAN_EXECUTE, "activate experimental balanced mode", 0, 1)
CreateConVar("ammokill_lower_limit_percent", 0, FCVAR_ARCHIVE + FCVAR_SERVER_CAN_EXECUTE, "the percentage of the clip that will serve as the lower limit for balanced mode", 0, 100)

hook.Add("PopulateToolMenu", "AmmoOnKill", function()
    spawnmenu.AddToolMenuOption("Utilities", "lemontine", "AmmoOnKill", "Ammo on Kill", "", "", function(panel)
        panel:ClearControls()
        if LocalPlayer():IsAdmin() or LocalPlayer():IsSuperAdmin() or game.SinglePlayer() then
            panel:Help("Server options")
            panel:CheckBox("Enable Ammo on Kill", "ammokill_enabled")
            panel:CheckBox("Only headshots give ammo?", "ammokill_headshots_only")
            panel:CheckBox("Should one-shots be counted as headshots?", "ammokill_overkills_are_headshots")
            panel:ControlHelp("")
            panel:NumSlider("Max primary ammo", "ammokill_primarymax", 0, 100, 0)
            panel:ControlHelp("Limits the number of primary mags replenishable by a kill")
            panel:NumSlider("Max secondary ammo", "ammokill_secondarymax", 0, 100, 0)
            panel:ControlHelp("Limits the number of secondary ammo replenishable by a kill")
            panel:NumSlider("Primary ammo per kill", "ammokill_primary_multiplier", 0, 10, 0)
            panel:ControlHelp("How many primary mags to give back per kill")
            panel:NumSlider("Alternate ammo per kill", "ammokill_secondary_multiplier", 0, 10, 0)
            panel:ControlHelp("How much secondary ammo to give back per kill")
            panel:CheckBox("Start with SMG alt ammo?", "ammo_start_with_smg_grenades")
            panel:ControlHelp("")
            panel:NumSlider("Ammo chance", "ammokill_chance", 0, 100, 2)
            panel:CheckBox("Alternative balance mode", "ammokill_balanced")
            panel:NumSlider("Percentage", "ammokill_lower_limit_percent", 0, 100, 2)
            panel:ControlHelp("Percentage of the clip that will serve as the lower limit for experimental balanced mode")
        end
        panel:Help("Client options")
        panel:CheckBox("Hide ammo pickups", "ammokill_hidden")
        panel:Help("(Made by lemontine)")
    end)
end)